language: node_js

node_js:
  - "11.10.1"

dist: trusty

sudo: false

install:
  - node --version
  - npm --version
  - npm i

script:
  - npm run lint
  - npm run test
  - npm run build

cache:
  directories:
    - node_modules
